language: python
python:
    - "2.7"

services:
    - rabbitmq

env:
    - ACTION="run-integration-tests"
    - ACTION="test-plugins"
    - ACTION="test-rest-service"
    - ACTION="flake8"
    - ACTION="plugin-installer-py26"

install:
    - pip install tox
script:
    - ./run-tests.sh $ACTION
